version: "3.9"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:1000"
    volumes:
      - ./config:/config:Z
      - ./cache:/cache:Z
      - /mnt/movies:/media:Z
      - /mnt/tvshows:/media2:Z
    environment:
      - JELLYFIN_PublishedServerUrl=0.0.0.0:8096
    ports:
      - "8096:8096"
      # - "8920:8920"   # Uncomment if you are using HTTPS
    extra_hosts:
      - "host.podman.internal:host-gateway"






